### ISSUE TITLE
Example with "customLanguages" config section needed

### ISSUE THREAD

**Issue by dkozar** [microsoft/monaco-editor-webpack-plugin#136]
Sorry for making this an issue, but it would be great if you could point me to a working example which is using the `customLanguages` config section.

This is related to the previous issue I reported: https://github.com/microsoft/monaco-editor-webpack-plugin/issues/135

Basically I'm working on the editor which has a custom language (let's call it "foo") and its worker. Here's the config section in `webpack.config`:

```js
new MonacoWebpackPlugin({
  languages: ['javascript'],
  customLanguages: [{
    label: 'foo',
    entry: undefined,
    worker: {
      id: 'foo-worker',
      entry: path.resolve(__dirname, '../node_modules/foo-library/dist/foo.worker.js')
    }
  }]
})
```

As you can see, my worker lives in another library (node_modules/foo-library). It is actually a typescript compiled to Javascript as UMD module.

However, I'd need some instructions on the `customLanguages `config. The documentation doesn't cover these in depth, so I don't understand what each of the above params do, and which ones are optional.

I'd really use a simplest example of a custom language that also uses a web worker. I searched the web, but was unable to find such an example. 

Any help much appreciated! Thanks! 😄

**Comment by alexdima** [comment]
`customLanguages` is an option that allows you to bundle another language in a similar way to the rest of the monaco editor bundling. This plugin makes it that languages are loaded in the editor only on demand. So for example, only a small piece regarding `css` is bundled in the main bundle, only a small piece regarding `json` is bundled in the main bundle, etc.

At runtime, when the editor actually ends up createing a `css` text buffer, it is going to fire a listener (`monaco.editor.onLanguage`) with that specific language id. e.g. https://github.com/microsoft/monaco-css/blob/ae46dfbebdf1e863c13e3ac4c8684399de34c929/src/monaco.contribution.ts#L215-L217

That listener will then do a dynamic import of the actual needed code for handling css e.g. here -- https://github.com/microsoft/monaco-css/blob/ae46dfbebdf1e863c13e3ac4c8684399de34c929/src/monaco.contribution.ts#L204

Eventually, that css specific code will register all kind of providers to the editor and in order to implement them, it will create a web worker e.g. here -- https://github.com/microsoft/monaco-css/blob/ae46dfbebdf1e863c13e3ac4c8684399de34c929/src/workerManager.ts#L57

For css specifically, here is how that language definition is filled: 
```
  {
    label: 'css',
    entry: [
      'vs/basic-languages/css/css.contribution',
      'vs/language/css/monaco.contribution'
    ],
    worker: {
      id: 'vs/language/css/cssWorker',
      entry: 'vs/language/css/css.worker'
    }
  },
```

The `entry` field contains what scripts should be included in the main bundle. In this case, only a small piece (the one that defines the language and the one that listens to the text buffer getting created is included) (`vs/language/css/monaco.contribution`). The css coloring is defined as a monarch grammar so that one is included as well (`vs/basic-languages/css/css.contribution`).

Now, regarding web workers. Webpack has had very poor support for picking up `new Worker()` calls from scripts. AFAIK only in recent versions they have become interested in covering that. That is why the worker section defines the css worker ESM entry point (`vs/language/css/css.worker`) -- https://github.com/microsoft/monaco-css/blob/master/src/css.worker.ts -- which will be bundled independently in a sepearate output bundle which will be complete.

**Comment by alexdima** [comment]
All of that being said, there is no need for you to use `customLanguages` at all. You can just define your bundles directly with webpack, you just need to make sure that the UI code ends up including your code too and that your web worker exists in bundled form.

**Comment by dkozar** [comment]
Thanks @alexdima, this was very helpful!

If I understand correctly, I don't need to provide the `MonacoEnvironment.getWorkerUrl` at all (in order for the worker to be loaded), as `monaco.editor.createWebWorker` does all the work (initiates loading of the worker chunk)?

Additionally, I have all the editor code in a separate library. This library is written in Typescript, and has to be consumed by web apps (for instance, an app built with React). My original intent was for the library was to bundle every worker and expose all the workers as compiled Javascript files. I'm not sure if this feasible or is there a smarter way to do it. I wouldn't like to expose Typescript files directly, because this implies a lot of configuration by the consumer (also, everything in _node_modules_ should probably be pure JS).

So the goal is to have a React component exposed by this package, that one be easily included in web app and put on screen. The user would just need to specify the language (`<Editor language="foo" />`), and couple of other props (like some API endpoints that each worker needs to communicate with) and that's it.

I'm interested in which approach would you suggest? I.e. if I have all the editor component code in a single repo, how would you configure Webpack in order to build something useful for consumers, where the usage and configuration would be as simple as possible?

Thanks! :)

**Comment by alexdima** [comment]
I am sorry, but we are going to have to ask the community and hope someone can chime in. I am not a webpack expert and I think my abilities with webpack have been reached by this question.

**Comment by alexdima** [comment]
@gavinxgu Since the support for `customLanguages` came initially from you via the PR https://github.com/microsoft/monaco-editor-webpack-plugin/pull/122 , do you perhaps have a sample project that you can share where you make use of this option as an example ?

**Comment by dkozar** [comment]
Thanks @alexdima! I managed to produce the right pieces of Webpack configuration:

```js
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');
const path = require('path');
const main = path.resolve(__dirname, './src/index.ts');
const mylang1 = path.resolve(__dirname, './src/workers/mylang1.ts');
const mylang2 = path.resolve(__dirname, './src/workers/mylang2.ts');

const getEntries = () => {
    "editor.worker": 'monaco-editor/esm/vs/editor/editor.worker.js',
    "mylang1.worker": mylang1,
    "mylang2.worker": mylang2,
}

const getMonacoPluginConfig = () => new MonacoWebpackPlugin({
    languages: ['javascript'],
    customLanguages: [{
        label: 'mylang1',
        entry: main,
        worker: {
            id: 'mylang1.worker',
            label: 'mylang1-worker',
            entry: mylang1
        }
    }, {
        label: 'mylang2',
        entry: main,
        worker: {
            id: 'mylang2.worker',
            label: 'mylang2-worker',
            entry: mylang2
        }
    }],
});
```

More info on how to load these workers at https://github.com/microsoft/monaco-editor-webpack-plugin/issues/135.

**Comment by djpate** [comment]
@dkozar Did you need to do anything else? I'm trying to get `monaco-graphql` to load but I cannot get the `getWorker` callback to fire. is `getEntries` needed? I don't see it used anywhere.

**Comment by dkozar** [comment]
> @dkozar Did you need to do anything else? I'm trying to get `monaco-graphql` to load but I cannot get the `getWorker` callback to fire. is `getEntries` needed? I don't see it used anywhere.

@djpate as far as I understand, neither the `getWorker` nor `getWorkerUrl` fire for custom languages (they are meant to be used with pre-built languages only).

Here's more info: https://github.com/microsoft/monaco-editor-webpack-plugin/issues/135

**Comment by JounQin** [comment]
@dkozar Why this option is not even mentioned in [README](https://github.com/microsoft/monaco-editor-webpack-plugin#options)?
