### ISSUE TITLE
monaco-editor generates a webpack bundle for each language 

### ISSUE THREAD

**Issue by afermi** [Microsoft/monaco-editor-webpack-plugin#43]
Hello everyone,

I am using react-monaco-editor with the monaco-editor-webpack-plugin to load the editor with webpack 4.20.2.
When I compile my code, each language generates its own bundle even though I passed as options of the plugin the array ["javascript", "typescript"].

How can I prevent this and only create bundles for the languages I want to use?

Thank you very much

**Comment by ulrichb** [comment]
Same here. 

Also `features: ['!toggleHighContrast', '!accessibilityHelp', '!contextmenu', '!codelens']` doesn't seem to work.

**Comment by micaww** [comment]
I have the same issue with the same setup. Is there any temporary workaround to force those bundles to not be generated?

**Comment by vianchen** [comment]
I ran into the same problem just a few minutes ago. I actually thought something was wrong with my webpack...

**Comment by micaww** [comment]
Hey all, I've found the issue.

Check out the [usage](https://github.com/Microsoft/monaco-editor-webpack-plugin#using) for Monaco Editor Webpack Plugin.

`react-monaco-editor` should be using:
```javascript
import * as monaco from 'monaco-editor/esm/vs/editor/editor.api'
```
but it uses
```javascript
import * as monaco from 'monaco-editor'
```
instead. This forces monaco-editor-webpack-plugin to build the entire editor instead of only what you tell it.

I've solved this issue by adding an alias for `monaco-editor` in my `webpack.config.js`:
```javascript
const path = require('path');
const webpack = require('webpack');
const MonacoEditorPlugin = require('monaco-editor-webpack-plugin');

module.exports = {
    mode: 'development',
    entry: './src/app.js',
    devtool: 'source-map',
    output: {
        path: path.resolve('dist'),
        filename: 'app.js'
    },
    module: {
        rules: [{
            test: /\.css$/,
            use: ['style-loader', 'css-loader']
        }]
    },
    // ALIAS
    resolve: {
        alias: {
            'monaco-editor': 'monaco-editor/esm/vs/editor/editor.api.js'
        }
    },
    plugins: [
        new MonacoEditorPlugin({
            languages: ['javascript', 'typescript'],
            features: []
        })
    ]
};
```

This issue should be closed as it has nothing to do with `monaco-editor-webpack-plugin`
