### ISSUE TITLE
Generated bundle names and loading bundle

### ISSUE THREAD

**Issue by DJBMASTER** [microsoft/monaco-editor-webpack-plugin#58]
I have set up the plugin using webpack.config.js:

```
"use strict";

// Required packages
const path = require("path");
const CleanWebpackPlugin = require("clean-webpack-plugin");
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');

// Variables
const rootOutputDir = "wwwroot/js";

module.exports = {

    entry: "./Scripts/Build/Pages/Home/Index.js",

    output: {
        filename: '[name].js',
        path: path.resolve(__dirname, rootOutputDir)
    },

    module: {
        rules: [
            {
                test: /\.jsx?$/,
                exclude: /node_modules/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: ['@babel/preset-env']
                    }
                }
            },
            {
                test: /\.css$/,
                use: ['style-loader', 'css-loader']
            }
        ]
    },

    resolve: {
        alias: {
            'monaco-editor': 'monaco-editor/esm/vs/editor/editor.api.js'
        }
    },

    plugins: [
        new CleanWebpackPlugin([rootOutputDir]),
        new MonacoWebpackPlugin({
            languages: ["xml"],
            features: ['wordHighlighter']
            })
    ]
};
```

This generated the following files in 'wwwroot/js':

```
0.js
editor.worker.js
main.js
```

I thought the point of this plugin and webpack in general was to bundle all the required modules into a single file. I have attempted to just load 'main.js' but it gives the following console errors:

`GET https://localhost:44303/0.js net::ERR_ABORTED 404`

It seems to be looking for the file in the root directory of my server rather than the place where it is generated which would be https://localhost:44303/js/0.js.

If I include all 3 scripts in my page everything is fine. So I have the following questions:

1) Why is my js file named '0.js'?
2) Do I need to include all files in my HTML page or is just including main.js supposed to work?
3) Why is the main.js looking for 0.js in the root of my webserver? Is there a path setting to modify this?

**Comment by frantic0** [comment]
Hi @DJBMASTER, I'm having the same problem. Did you made some improvement in your configuration?

There seems to be a bug as such output doesn't make sense when using a bundler...  

In my case, with the following webpack.config.js

```
// Required packages
const path = require("path");
const CleanWebpackPlugin = require("clean-webpack-plugin");
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');

const outputDir = "./build/";

module.exports = {
  mode: 'development',
  entry: './src/index.js',
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, outputDir)
  },
  module: {
    rules: [{
      test: /\.css$/,
      use: ['style-loader', 'css-loader']
    }]
  },
  plugins: [
    new CleanWebpackPlugin([outputDir]),
    new MonacoWebpackPlugin({
      languages: ['javascript', 'typescript', 'handlebars', 'html', 'css']
    })
  ]
};
```



I'm having the following list

```
0.bundle.js
1.bundle.js
2.bundle.js
3.bundle.js
4.bundle.js
5.bundle.js
6.bundle.js
7.bundle.js
bundle.js
css.worker.js
editor.worker.js
html.worker.js
typescript.worker.js
```

It seems that this plugin is not being maintained... Am

**Comment by DJBMASTER** [comment]
Hi @frantic0,

After not getting anywhere with WebPack, I have decided to move to using Parcel. Using parcel, monaco is bundled correctly and I only have to include 'index.js' on my page - all language files and editor features/workers are included automatically.

I recommend giving Parcel a try; It's much easier to setup and the learning curve isn't as steep.

**Comment by ije** [comment]
i got the same issue and i got *0.js* ~ *64.js*...
i guess the monaco-editor-webpack-plugin creates a pile of async chunks, you can try to bundle those async chunks to one file by using **splitChunks** optimization options:

```javascript
module.exports = {
   ...
   optimization: {
        splitChunks: {
            cacheGroups: {
                monacoCommon: {
                    test: /[\\/]node_modules[\\/]monaco\-editor/,
                    name: 'monaco-editor-common',
                    chunks: 'async'
                }
            }
        }
   }
   ...
}
```

in my project, it will pack *0.js* ~ *64.js* to *monaco-editor-common.js*.

**Comment by VAllens** [comment]
> i got the same issue and i got _0.js_ ~ _64.js_...
> i guess the monaco-editor-webpack-plugin creates a pile of async chunks, you can try to bundle those async chunks to one file by using **splitChunks** optimization options:
> 
> ```js
> module.exports = {
>    ...
>    optimization: {
>         splitChunks: {
>             cacheGroups: {
>                 monacoCommon: {
>                     test: /[\\/]node_modules[\\/]monaco\-editor/,
>                     name: 'monaco-editor-common',
>                     chunks: 'async'
>                 }
>             }
>         }
>    }
>    ...
> }
> ```
> 
> in my project, it will pack _0.js_ ~ _64.js_ to _monaco-editor-common.js_.

But there is a relative path problem. My `monaco-editor` library is in `rootPath/lib/monaco-editor`, and I reference it in `rootPath/project/settings/scripts/index.js`.
I have to copy `rootPath/lib/monaco-editor/monaco-editor-common.js` to `rootPath/project/settings/lib/monaco-editor/monaco-editor-common.js` so that it can be accessed to fix the `404` problem.

**Comment by ije** [comment]
@VAllens  maybe you need `publicPath` https://webpack.js.org/configuration/output/#outputpublicpath

**Comment by VAllens** [comment]
@ije

> @VAllens maybe you need `publicPath` https://webpack.js.org/configuration/output/#outputpublicpath

When I set this option, it works normally on the `webpack-dev-server`.
But when I publish to the production environment, the relative path problem appeared again.
Because in the development environment, it is the main site (sample: http://localhost:8080/project/settings/scripts/index.js).
But in the production environment, it's a sub-site (sample: http://www.prod-site.com/xxx/xxx/xxx/xxx/xxx/xxx/project/settings/scripts/index.js).

**Comment by alexdima** [comment]
Hi everyone, this plugin is working as intended in this case.

When running `npm run test` in this project, the editor will be webpacked and the following files will be generated:
* `app.js`
* `0.app.js` - `53.app.js`
* `editor.worker.js`, `css.worker.js`, `html.worker.js`, `json.worker.js`, `ts.worker.js`

This is intentional. Here is why:
- The main `app.js` contains the editor aware of all the languages, but **without any languages preloaded**
- That means that the editor knows about the 50+ languages it ships with, but it only knows that they exist and does not have loaded their definition.
- Only at runtime, if you create an editor and use the language `python`, the language definition for `python` will be loaded from (on my machine) `35.app.js`.
- Also, the editor will create web workers for some basic things that take a long time to compute on the UI, such as computing diff information, finding links, or doing word suggestions. That is why `editor.worker.js` is needed and loaded separately from the main UI thread in a web worker.
- For some languages, like `css`, when you create an editor that uses `css`, a web worker that knows how to deal with `css` ASTs will be created from `css.worker.js`.

---

If you want only a subset of the languages, say you know at runtime you only use `python`, you can configure the plugin to only ship `python`, e.g.:

* `webpack.config.js`:
```
    ...
    plugins: [
        new MonacoWebpackPlugin({
            languages: ['python']
        })
    ]
    ...
```

In this case only the following files are generated:
* `app.js`
* `0.app.js`
* `editor.worker.js`

The `app.js` contains again the editor, but in this case aware only of `python`, but **without `python` preloaded**. At runtime, only when the first editor is instantiated with the language `python`, then the `0.app.js` will be loaded. If you wish to preload that, you can do so by adding an import in your code:

* `app.js`:
```
import * as monaco from 'monaco-editor/esm/vs/editor/editor.api';
import 'monaco-editor/esm/vs/basic-languages/python/python';

monaco.editor.create(document.getElementById('container'), {
    value: 'console.log("Hello, world")',
    language: 'javascript'
}); 
```

In this case only the following files are generated:
* `app.js`
* `editor.worker.js`

The `app.js` contains again the editor, **with `python` preloaded**, so the python language definition is embedded inside `app.js`. The `editor.worker.js` will be dynamically created when you open your first file and have link highlighting enabled, or if you create a diff editor, etc.
