### ISSUE TITLE
Support __webpack_public_path__

### ISSUE THREAD

**Issue by rgbkrk** [microsoft/monaco-editor-webpack-plugin#7]
We've made good use of this plugin in https://github.com/nteract/nteract/pull/2779. We're running into one major issue though -- when we host our app on a subpath it appears that Monaco's webworkers aren't loading based on the `__webpack_public_path__`, instead relying only on the static `publicPath` in the webpack config.

What would we need to do to make monaco recognize the dynamic public path?

cc @yuvipanda

**Comment by dmitriylyner** [comment]
@rgbkrk This was recently fixed here: https://github.com/Microsoft/monaco-editor-webpack-plugin/pull/14

**Comment by rgbkrk** [comment]
🙏 Thank you!

**Comment by rgbkrk** [comment]
We dynamically set the `__webpack_public_path__` well before monaco is loaded (it loads in a chunk, dynamically imported, much later).

**Comment by akihikodaki** [comment]
Confirmed the problem. It incorrectly refers to `window.__webpack_public_path__`.

**Comment by z1haze** [comment]
> We dynamically set the `__webpack_public_path__` well before monaco is loaded (it loads in a chunk, dynamically imported, much later).

Could  you provide an example of how you're going about setting the __webpack_public_path__ before monaco-editor-webpack-plugin initializes? I don't see how that is feasible as at least in my situation the webpack public path variable is set  at runtime.

I end up with files in the correct location but instead of webpack looking for files in the correct public path, it looks for them a domain.com/js/worker.js when in reality it is domain.com/multi-site-name/default/some-version-hash/js/worker.js. We need this plugin to respect the runtime setting of __webpack_public_path__

**Comment by nmaoez** [comment]
We wanted to provide an app which is loadable from any path, so therefore we dynamically determine the base path on runtime and use it as `__webpack_public_path__`. The determination happens in the `index.html` and afterwards based on the determined base path the `bundle.js` is loaded.

So therefore we also had the problem loading the `editor.worker.js` file.
We managed to overcome this problem by overriding the `getWorkerUrl` in the `MonacoEnvironment `object like this:

´´´javascript
window.MonacoEnvironment = {
  getWorkerUrl(moduleId, label) {
    return `${BASE_PATH}${label == 'javascript' ? 'typescript' : 'editor'}.worker.js`;
  }
};
´´´

If you want to provide more languages then you have to consider more workers (see [issue](https://github.com/Microsoft/monaco-editor-webpack-plugin/issues/32)).
As long as this issue and the subsequent [PR](https://github.com/microsoft/monaco-editor-webpack-plugin/pull/63) is open, this can be considered as an alternative solution.

I hope this helps some people.
