### ISSUE TITLE
Ignoring 'fs' breaks electron

### ISSUE THREAD

**Issue by domoritz** [microsoft/monaco-editor-webpack-plugin#9]
In order to use monaco in electron, we need the `fs` module. We noticed that this module is being ignored by monaco-editor-webpack-plugin in https://github.com/Microsoft/monaco-editor-webpack-plugin/blob/v1.1.0/index.js#L8. How do we not ignore `fs` in our webpack builds? 

See https://github.com/superRaytin/react-monaco-editor/pull/111

**Comment by kqadem** [comment]
Instead using webpack-plugin u have to do it bundle it on your own, which is not that hard :)
You can find samples [here](https://github.com/Microsoft/monaco-editor/blob/master/docs/integrate-esm.md), [here](https://github.com/Microsoft/monaco-editor-samples/tree/master/browser-esm-webpack-small) and [here](https://github.com/Microsoft/monaco-editor-samples/tree/master/browser-esm-webpack)


Ignoriing the fs module makes no sense in your case...The trick for me back then was to play around with the ```target``` [option in webpack](https://webpack.js.org/configuration/target/). There were example codes but the repos are deleted somehow...Maybe you'll figure it out :)

**Comment by timkendrick** [comment]
As far as I can tell, this issue arises because `typescriptServices.js` is a universal module that can be used either in a Node environment (e.g. by the `tsc` compiler), or in a browser environment (e.g. providing language services to Monaco editor). When running in a Node environment, it uses `fs` etc to provide various extra functionality, whereas in the browser these features will be disabled.

`typescriptServices.js` determines the runtime environment based on [this check](https://github.com/Microsoft/TypeScript/blob/e53e56cf8212e45d0ebdd6affe462d161c7e0dc5/src/compiler/sys.ts#L1145-L1149):
```
        else if (typeof process !== "undefined" && process.nextTick && !process.browser && typeof require !== "undefined") {
            // process and process.nextTick checks if current environment is node-like
            // process.browser check excludes webpack and browserify
            sys = getNodeSystem();
        }
```

This issue arises because webpack automatically [assigns `process.browser` for the `web` target ](https://github.com/webpack/webpack/blob/603cb60b00e0075acb2c623576368f203a8864a0/lib/WebpackOptionsApply.js#L88) as part of the node globals polyfill, however it appears it doesn't do this for the `electron-renderer` target (presumably because it already has [its own `process` object](https://electronjs.org/docs/api/process)).

So for a workaround, you can continue to use the monaco plugin within electron by manually defining the `process.browser` variable in your webpack config:

```
plugins: [
  ...
  new webpack.DefinePlugin({
    'process.browser': true,
  }),
  new MonacoWebpackPlugin({
    output: 'static/monaco',
  }),
  ...
],
```

As for a more long-term fix, the easiest option would be for the monaco editor plugin to add the `DefinePlugin` internally – however this has the potential to break any other unrelated modules that are relying on `process.browser` being false for the `electron-renderer` target.

Ideally I suppose `typescriptServices` could be changed to detect whether it is running in an electron renderer environment, rather than just relying on `process.browser`. From looking at the electron [`process.type` docs](https://electronjs.org/docs/api/process#processtype), it seems like the current [`!process.browser` test in `sys.ts`](https://github.com/Microsoft/TypeScript/blob/e53e56cf8212e45d0ebdd6affe462d161c7e0dc5/src/compiler/sys.ts#L1145) could be changed to the following:

`else if (typeof process !== "undefined" && process.nextTick && !(process.browser || process.type === "renderer") && typeof require !== "undefined") {`

What do you reckon @alexandrudima?

**Comment by alexandrudima** [comment]
I wanted to avoid patching the guts of that file, but I guess it is not avoidable anymore.

We already patch `typescriptServices.js` [here](https://github.com/Microsoft/monaco-typescript/blob/5c1bcb6ae36b00ecb7011b559486ca1b0d3b8398/scripts/importTypescript.js) to make it an ESM module. I think we could simply replace all `require` calls with something else (to avoid webpack finding them) and we can ensure that if stmt is always false.

**Comment by timkendrick** [comment]
How about adding an upstream change to the `Microsoft/TypeScript` repo that changes this line? They're already adding in special behavior for the non-standard `process.browser` webpack runtime variable, so it seems sensible to cater for the webpack electron case there as well…

**Comment by alexandrudima** [comment]
Our scripts need to massage `typescriptServices.js` anyways for ESM purposes.

I have an easy change that removes the entire `ts.system` block. That should result in our being able to remove the usage of the `IgnorePlugin` entirely for `typescriptServices.js` and from all the webpack examples.

https://github.com/Microsoft/monaco-typescript/commit/c7b54325fd700fe5c44849a11a8e549296b03951

**Comment by alexdima** [comment]
This has been resolved in the meantime by massaging `typescriptServices.js` and now we don't use `IgnorePlugin` anymore.
